In [1]:
import os
from dotenv import load_dotenv
from openai import OpenAI


# ============================================================
# 1. LOAD API KEY
# ============================================================

load_dotenv()

client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY")
)


# ============================================================
# 2. AI TEACHER INSTRUCTIONS
# ============================================================

TEACHER_INSTRUCTIONS = """
You are an expert AI Teacher.

Your job is to teach students, not just provide answers.

Teaching rules:
Give only simple explanation of the concept with layman terms.
Answer should be precise 3 lines.
Response format:
Explain the concept simply.
"""


# ============================================================
# 3. CONVERSATION MEMORY
# ============================================================

conversation = [
    {
        "role": "developer",
        "content": TEACHER_INSTRUCTIONS
    }
]


# ============================================================
# 4. AI TEACHER FUNCTION
# ============================================================

def ask_teacher(
    question,
    subject="AI & Data Science",
    student_level="Beginner",
    language="English"
):

    user_message = f"""
Subject: {subject}

Student Level: {student_level}

Preferred Language: {language}

Student Question:
{question}
"""

    conversation.append({
        "role": "user",
        "content": user_message
    })

    response = client.responses.create(
        model="gpt-5.6-luna",
        input=conversation
    )

    answer = response.output_text

    conversation.append({
        "role": "assistant",
        "content": answer
    })

    return answer


# ============================================================
# 5. CHAT APPLICATION
# ============================================================

def start_teacher():

    print("=" * 60)
    print("              AI TEACHER")
    print("=" * 60)

    print("Type 'exit' to stop.\n")

    while True:

        question = input("Student: ")

        if question.lower() == "exit":

            print("\nTeacher: Keep learning! 👋")
            break

        answer = ask_teacher(
            question=question,
            subject="AI & Data Science",
            student_level="Beginner",
            language="English"
        )

        print("\nTeacher:")
        print(answer)

        print("\n" + "-" * 60)


# ============================================================
# 6. RUN
# ============================================================

if __name__ == "__main__":
    start_teacher()

============================================================
              AI TEACHER
============================================================
Type 'exit' to stop.

Student:  what is AI?

Teacher:
AI (Artificial Intelligence) is the ability of computers to think, learn, and make decisions like humans.
It uses data and rules to solve problems, recognize patterns, and perform tasks.
Examples include voice assistants, recommendation systems, and self-driving cars.

------------------------------------------------------------

Student:  tell about Machine leanering

Teacher:
Machine learning is a part of AI where computers learn from data and improve without being directly programmed for every task.
It finds patterns in examples to make predictions or decisions.
Examples include spam detection, movie recommendations, and face recognition.

------------------------------------------------------------

Student:  exit

Teacher: Keep learning! 👋

# Stage2 -  input Quries- Generate

In [2]:
import os
import pandas as pd
from dotenv import load_dotenv
from openai import OpenAI


# ============================================================
# 1. LOAD ENVIRONMENT
# ============================================================

load_dotenv()

client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY")
)


# ============================================================
# 2. FILE CONFIGURATION
# ============================================================

INPUT_CSV = "ai_teacher_20_questions.csv"
OUTPUT_CSV = "ai_teacher_results.csv"


# ============================================================
# 3. LOAD DATASET
# ============================================================

df = pd.read_csv(INPUT_CSV)

print("Dataset loaded")
print(f"Number of questions: {len(df)}")


# ============================================================
# 4. AI TEACHER INSTRUCTIONS
# ============================================================

TEACHER_INSTRUCTIONS = """
You are an expert AI Teacher.

Your job is to teach students, not just provide answers.

Teaching rules:
Give only simple explanation of the concept with layman terms.
Answer should be precise 3 lines.
Response format:
Explain the concept simply.
"""


# ============================================================
# 5. GENERATE ANSWER
# ============================================================

def generate_answer(question):

    response = client.responses.create(
        model="gpt-5.6-luna",
        instructions=TEACHER_INSTRUCTIONS,
        input=question
    )

    return response.output_text.strip()


# ============================================================
# 6. GENERATE ANSWERS FOR ALL QUESTIONS
# ============================================================

generated_answers = []

for index, row in df.iterrows():

    question = row["User Query"]

    print(f"Processing {index + 1}/{len(df)}")
    print(f"Question: {question}")

    try:

        answer = generate_answer(question)

    except Exception as e:

        answer = f"ERROR: {str(e)}"

    generated_answers.append(answer)


# ============================================================
# 7. APPEND GENERATED ANSWER TO DATAFRAME
# ============================================================

df["GeneratedAnswer"] = generated_answers


# ============================================================
# 8. SELECT FINAL COLUMNS
# ============================================================

df = df[
    [
        "User Query",
        "Teacher Response",
        "GeneratedAnswer"
    ]
]


# ============================================================
# 9. SAVE RESULT
# ============================================================

df.to_csv(
    OUTPUT_CSV,
    index=False,
    encoding="utf-8-sig"
)


# ============================================================
# 10. DISPLAY RESULT
# ============================================================

print("\n" + "=" * 70)
print("AI TEACHER TEST COMPLETED")
print("=" * 70)

print(df.to_string(index=False))

print("\nResult saved to:")
print(OUTPUT_CSV)

Dataset loaded
Number of questions: 20
Processing 1/20
Question: What is AI?
Processing 2/20
Question: How does AI differ from traditional programming?
Processing 3/20
Question: What is Machine Learning?
Processing 4/20
Question: What is Deep Learning?
Processing 5/20
Question: What is the difference between AI, ML, and Deep Learning?
Processing 6/20
Question: What is training data?
Processing 7/20
Question: What is a Machine Learning model?
Processing 8/20
Question: What is supervised learning?
Processing 9/20
Question: What is unsupervised learning?
Processing 10/20
Question: What is reinforcement learning?
Processing 11/20
Question: What is an LLM?
Processing 12/20
Question: What is Generative AI?
Processing 13/20
Question: What is a prompt?
Processing 14/20
Question: What is Prompt Engineering?
Processing 15/20
Question: What is RAG?
Processing 16/20
Question: Why is RAG useful?
Processing 17/20
Question: What is a vector database?
Processing 18/20
Question: What are embeddings?
Processing 19/20
Question: What is an AI Agent?
Processing 20/20
Question: How can AI be used in education?

======================================================================
AI TEACHER TEST COMPLETED
======================================================================
                                               User Query                                                                                                                                                                             Teacher Response                                                                                                                                                                                                                                                                                                                           GeneratedAnswer
                                              What is AI? AI (Artificial Intelligence) is the ability of computers to perform tasks that normally require human intelligence, such as learning, reasoning, recognizing patterns, and making decisions.                                     AI (Artificial Intelligence) is technology that enables computers to learn, think, and make decisions like humans.  \nIt can recognize images, understand language, solve problems, and perform tasks.  \nExamples include chatbots, voice assistants, recommendation systems, and self-driving cars.
         How does AI differ from traditional programming?                                  Traditional programs follow fixed rules written by humans. AI systems can learn patterns from data and use those patterns to make predictions or decisions.                                           Traditional programming follows explicit rules written by humans to produce outputs from inputs.  \nAI learns patterns from examples and uses them to make predictions or decisions.  \nIn short: traditional programs are rule-based, while AI is data-driven and can improve with experience.
                                What is Machine Learning?      Machine Learning is a branch of AI where computers learn patterns from data and use those patterns to make predictions or decisions without being explicitly programmed for every case.                                                                     Machine Learning is a way for computers to learn from examples and data.  \nInstead of being explicitly programmed for every task, the computer finds patterns and makes predictions.  \nFor example, it can learn to identify spam emails by studying many examples.
                                   What is Deep Learning?                                             Deep Learning is a type of Machine Learning that uses neural networks with multiple layers to learn complex patterns from large amounts of data.                                   Deep Learning is a type of AI that uses artificial neural networks to learn from large amounts of data.  \nIt finds patterns by processing information through layers, similar to how the brain learns.  \nFor example, it helps computers recognize faces, understand speech, and translate languages.
What is the difference between AI, ML, and Deep Learning?                  AI is the broad field of making machines intelligent. ML is a way to achieve AI by learning from data. Deep Learning is a type of ML that uses multi-layer neural networks.  AI is the broad idea of making computers perform tasks that normally require human intelligence.  \nMachine Learning (ML) is a part of AI where computers learn patterns from data instead of being directly programmed.  \nDeep Learning is a type of ML that uses layered neural networks to learn from large amounts of complex data.
                                   What is training data?                                            Training data is the data used to teach a Machine Learning model. The model studies patterns in this data so it can make predictions on new data.                                                                                               Training data is the information used to teach an AI system how to perform a task.  \nIt can include text, images, audio, or other examples with useful patterns.  \nThe AI studies these examples to make better predictions or decisions.
                        What is a Machine Learning model?                                        A Machine Learning model is a mathematical system that learns patterns from data and uses those learned patterns to produce predictions or decisions.                                                       A machine learning model is a computer program that learns patterns from examples or data.  \nIt uses these learned patterns to make predictions or decisions about new information.  \nFor example, it can learn from labeled photos to recognize whether a new photo shows a cat.
                             What is supervised learning?                           Supervised learning trains a model using examples that already have known answers, such as customer information paired with whether the customer left the company.                                                             Supervised learning is a type of machine learning that learns from examples with known answers.  \nIt studies input data and correct labels to learn how to make predictions.  \nFor example, learning from labeled pictures to identify whether an image shows a cat or dog.
                           What is unsupervised learning?                                        Unsupervised learning works with data that does not have predefined answers. The model tries to discover patterns, groups, or structures in the data.                                                                        Unsupervised learning is a type of machine learning where the computer learns from data without labeled answers.  \nIt finds hidden patterns, groups, or relationships in the data by itself.  \nFor example, it can group customers with similar shopping habits.
                          What is reinforcement learning?                                                      Reinforcement learning teaches an agent through rewards and penalties. The agent learns which actions produce better results over time.                                                                                                         Reinforcement learning is a type of machine learning where an agent learns by trying actions.  \nIt receives rewards for good actions and penalties for bad ones.  \nOver time, it learns which actions lead to the best results.
                                          What is an LLM?                                                             An LLM, or Large Language Model, is an AI model trained on large amounts of text to understand and generate human-like language.                                                                    An LLM (Large Language Model) is an AI trained on huge amounts of text.  \nIt learns patterns in language to understand questions and generate human-like answers.  \n“Large” means it has many learned parameters, and “language model” means it works with language.
                                   What is Generative AI?                                                       Generative AI is AI that can create new content such as text, images, audio, video, or code based on patterns learned during training.                                                         Generative AI is technology that creates new content, such as text, images, music, or videos.  \nIt learns patterns from existing examples and uses them to produce something new.  \nFor example, ChatGPT generates answers by predicting suitable words based on your question.
                                        What is a prompt?                                       A prompt is the instruction or input given to an AI model to tell it what you want it to do, such as explain a concept, write code, or summarize text.                                                                                                                                                                A prompt is a question, instruction, or message given to an AI.  \nIt tells the AI what you want it to do or answer.  \nExample: “Explain photosynthesis in simple words.”
                              What is Prompt Engineering?                                                 Prompt Engineering is the practice of designing clear and effective instructions so an AI model produces more useful and reliable responses.                                                                   Prompt engineering is the skill of writing clear instructions for an AI to get the result you want.  \nIt involves specifying the task, context, desired format, and important details.  \nFor example: “Explain photosynthesis in three simple sentences for a child.”
                                             What is RAG?             RAG stands for Retrieval-Augmented Generation. It retrieves relevant information from external data sources and provides that information to an LLM before generating an answer.                               RAG (Retrieval-Augmented Generation) helps AI answer using information retrieved from documents or databases.  \nIt first searches for relevant facts, then uses them to create a more accurate response.  \nThis reduces made-up answers and keeps responses connected to current or specific information.
                                       Why is RAG useful?                              RAG is useful when an AI application needs to answer questions using specific or changing information, such as company documents, policies, or knowledge bases.                                                                                                                            RAG lets an AI search trusted documents before writing an answer.  \nThis helps it give more accurate, current, and relevant information.  \nIt also reduces made-up answers and can use private company data.
                               What is a vector database?                                         A vector database stores numerical representations called embeddings and allows applications to search for information based on semantic similarity. A vector database stores information as number-based representations called vectors, which capture meaning and similarity.  \nIt lets systems quickly find related items, such as similar documents, images, products, or questions.  \nFor example, it can find an answer with the same meaning even when the exact words are different.
                                     What are embeddings?                 Embeddings are numerical representations of text, images, or other data. Similar meanings tend to have similar vector representations, which makes semantic search possible.                                              Embeddings are numbers that represent words, images, or other data in a way computers can understand.  \nSimilar things get similar number patterns, so computers can compare meanings or features.  \nFor example, “cat” and “kitten” have embeddings that are closer than “cat” and “car.”
                                     What is an AI Agent?                            An AI Agent is a system that can understand a goal, decide what actions are needed, use tools when necessary, and work through multiple steps to complete a task.                                             An AI agent is a computer program that can understand a goal and decide what actions to take.  \nIt observes information, reasons about it, and uses tools or systems to complete tasks.  \nFor example, a virtual assistant can answer questions, schedule meetings, or send emails for you.
                         How can AI be used in education?        AI can support education by explaining concepts, generating practice questions, adapting lessons to student levels, providing feedback, and helping students learn at their own pace.                                                  AI can personalize lessons by adapting to each student’s level, pace, and learning style.  \nIt can help teachers create materials, grade work, and identify areas where students need support.  \nAI should assist teachers, not replace them, and must be used fairly and responsibly.

Result saved to:
ai_teacher_results.csv

# Stage3 - LLM Evaluation- Answer Quality

In [3]:
import pandas as pd

from deepeval import evaluate
from deepeval.metrics import AnswerRelevancyMetric, GEval
from deepeval.test_case import LLMTestCase, SingleTurnParams
from deepeval.evaluate import AsyncConfig

# ============================================================
# 1. LOAD DATA
# ============================================================

df = pd.read_csv("ai_teacher_results.csv")


# ============================================================
# 2. CREATE TEST CASES
# ============================================================

test_cases = [
    LLMTestCase(
        input=row["User Query"],
        actual_output=row["GeneratedAnswer"],
        expected_output=row["Teacher Response"]
    )
    for _, row in df.iterrows()
]


# ============================================================
# 3. DEFINE METRICS
# ============================================================

correctness = GEval(
    name="Answer Correctness",

    model="gpt-4.1",

    criteria="""
    Evaluate whether the generated answer is factually correct
    compared with the expected teacher answer.

    Give a high score when the important meaning and facts are correct.

    Penalize:
    - incorrect facts
    - contradictory information
    - missing important information

    Minor wording differences should not reduce the score.
    """,

    evaluation_params=[
        SingleTurnParams.ACTUAL_OUTPUT,
        SingleTurnParams.EXPECTED_OUTPUT
    ],

    async_mode=AsyncConfig(run_async=False)
)


relevancy = AnswerRelevancyMetric(
    model="gpt-4.1",

    include_reason=False,

    async_mode=False
)


helpfulness = GEval(
    name="Helpfulness",

    model="gpt-4.1",

    criteria="""
    Evaluate how helpful the generated answer is for a beginner student.

    A helpful answer should:

    1. Directly answer the student's question.
    2. Be easy to understand.
    3. Provide enough explanation.
    4. Avoid unnecessary information.
    5. Help the student understand the concept.
    """,

    evaluation_params=[
        SingleTurnParams.INPUT,
        SingleTurnParams.ACTUAL_OUTPUT
    ],

    async_mode=AsyncConfig(run_async=False)
)


# ============================================================
# 4. RUN DEEPEVAL
# ============================================================

result = evaluate(
    test_cases=test_cases,

    metrics=[
        correctness,
        relevancy,
        helpfulness
    ],

    # IMPORTANT FOR JUPYTER / ANACONDA
    async_config=AsyncConfig(run_async=False)
)

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_1 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_2 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_3 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_4 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_5 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_6 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_7 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_8 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_9 (Passed 3 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_10 (Passed 3 metrics)                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_11 (Passed 3 metrics)                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_12 (Passed 3 metrics)                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_13 (Passed 3 metrics)                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_14 (Passed 3 metrics)                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_15 (Passed 3 metrics)                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_16 (Passed 3 metrics)                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_17 (Passed 3 metrics)                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_18 (Passed 3 metrics)                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_19 (Passed 3 metrics)                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                              ┃ Average Score      ┃ Pass Rate                                ┃ Total    │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━ │
│  Answer Correctness [GEval]          │ 0.89               │ 100.00% | passed=20 | failed=0           │ 20       │
│  Answer Relevancy                    │ 0.98               │ 100.00% | passed=20 | failed=0           │ 20       │
│  Helpfulness [GEval]                 │ 0.99               │ 100.00% | passed=20 | failed=0           │ 20       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=707014;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 251.72s | token cost: 0.127002 USD)
» Test Results (20 total tests):
   » Pass Rate: 100.0% | Passed: 20 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

In [4]:
dir(result)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__class_getitem__',
 '__class_vars__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__fields__',
 '__fields_set__',
 '__format__',
 '__ge__',
 '__get_pydantic_core_schema__',
 '__get_pydantic_json_schema__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__pretty__',
 '__private_attributes__',
 '__pydantic_complete__',
 '__pydantic_computed_fields__',
 '__pydantic_core_schema__',
 '__pydantic_custom_init__',
 '__pydantic_decorators__',
 '__pydantic_extra__',
 '__pydantic_extra_info__',
 '__pydantic_fields__',
 '__pydantic_fields_set__',
 '__pydantic_generic_metadata__',
 '__pydantic_init_subclass__',
 '__pydantic_on_complete__',
 '__pydantic_parent_namespace__',
 '__pydantic_post_init__',
 '__pydantic_private__',
 '__pydantic_root_model__',
 '__pydantic_serializer__',
 '__pydantic_setattr_handlers__',
 '__pydantic_validator__',
 '__reduce__',
 '__reduce_ex__',
 '__replace__',
 '__repr__',
 '__repr_args__',
 '__repr_name__',
 '__repr_recursion__',
 '__repr_str__',
 '__rich_repr__',
 '__setattr__',
 '__setstate__',
 '__signature__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_calculate_keys',
 '_copy_and_set_values',
 '_get_value',
 '_iter',
 '_setattr_handler',
 'confident_link',
 'construct',
 'copy',
 'dict',
 'from_orm',
 'json',
 'model_computed_fields',
 'model_config',
 'model_construct',
 'model_copy',
 'model_dump',
 'model_dump_json',
 'model_extra',
 'model_fields',
 'model_fields_set',
 'model_json_schema',
 'model_parametrized_name',
 'model_post_init',
 'model_rebuild',
 'model_validate',
 'model_validate_json',
 'model_validate_strings',
 'parse_file',
 'parse_obj',
 'parse_raw',
 'schema',
 'schema_json',
 'test_results',
 'test_run_id',
 'update_forward_refs',
 'validate']

In [6]:
result.test_results

[TestResult(name='test_case_0', success=True, metrics_data=[MetricData(name='Answer Correctness [GEval]', threshold=0.5, success=True, score=0.8901920667961543, reason='The Actual Output accurately conveys the main facts from the Expected Output, including that AI enables computers to perform tasks requiring human intelligence, such as learning, reasoning, and decision-making. It also adds relevant examples and details like image recognition and language understanding, which align with the intent of the Expected Output. There are no incorrect facts or contradictions, but the Actual Output is slightly more detailed than required, which does not detract from accuracy.', strict_mode=False, flaky=False, evaluation_model='gpt-4.1', error=None, evaluation_cost=0.0026379999999999997, input_tokens=595, output_tokens=181, verbose_logs='Criteria:\n\n    Evaluate whether the generated answer is factually correct\n    compared with the expected teacher answer.\n\n    Give a high score when the important meaning and facts are correct.\n\n    Penalize:\n    - incorrect facts\n    - contradictory information\n    - missing important information\n\n    Minor wording differences should not reduce the score.\n     \n \nEvaluation Steps:\n[\n    "Compare the Actual Output to the Expected Output to check if all important facts and information are correct and present.",\n    "Identify any incorrect facts, contradictions, or missing key information in the Actual Output compared to the Expected Output.",\n    "Ignore minor wording differences that do not affect the meaning or factual accuracy.",\n    "Assign a high score if the Actual Output accurately conveys the important meaning and facts from the Expected Output."\n] \n \nRubric:\nNone \n \nScore: 0.8901920667961543'), MetricData(name='Answer Relevancy', threshold=0.5, success=True, score=1.0, reason=None, strict_mode=False, flaky=False, evaluation_model='gpt-4.1', error=None, evaluation_cost=0.004354, input_tokens=885, output_tokens=323, verbose_logs='Statements:\n[\n    "AI stands for Artificial Intelligence.",\n    "AI is technology that enables computers to learn, think, and make decisions like humans.",\n    "AI can recognize images.",\n    "AI can understand language.",\n    "AI can solve problems.",\n    "AI can perform tasks.",\n    "Examples of AI include chatbots, voice assistants, recommendation systems, and self-driving cars."\n] \n \nVerdicts:\n[\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "idk",\n        "reason": "While image recognition is a capability of AI, the statement is more of an example rather than a direct definition of what AI is."\n    },\n    {\n        "verdict": "idk",\n        "reason": "Understanding language is a capability of AI, but the statement is an example rather than a direct explanation of what AI is."\n    },\n    {\n        "verdict": "idk",\n        "reason": "Solving problems is a function of AI, but this is an example of what AI can do, not a definition."\n    },\n    {\n        "verdict": "idk",\n        "reason": "Performing tasks is a general capability of AI, but the statement does not define AI directly."\n    },\n    {\n        "verdict": "idk",\n        "reason": "Listing examples of AI applications provides supporting information, but does not directly answer what AI is."\n    }\n]'), MetricData(name='Helpfulness [GEval]', threshold=0.5, success=True, score=1.0, reason='The response directly answers the question by defining AI in simple terms, making it accessible for a beginner. It provides clear examples and explains key capabilities of AI, helping the student understand the concept. The explanation is concise and avoids irrelevant information.', strict_mode=False, flaky=False, evaluation_model='gpt-4.1', error=None, evaluation_cost=0.002048, input_tokens=544, output_tokens=120, verbose_logs='Criteria:\n\n    Evaluate how helpful the generated answer is for a beginner student.\n\n    A helpful answer should:\n\n    1. Directly answer the student\'s question.\n    2. Be easy to understand.\n    3. Provide enough explanation.\n    4. Avoid unnecessary information.\n    5. Help the student understand the concept.\n     \n \nEvaluation Steps:\n[\n    "Check if the Actual Output directly answers the question in the Input.",\n    "Assess whether the Actual Output is easy to understand for a beginner student.",\n    "Determine if the Actual Output provides sufficient explanation to help the student grasp the concept.",\n    "Verify that the Actual Output avoids unnecessary or irrelevant information."\n] \n \nRubric:\nNone \n \nScore: 1.0')], conversational=False, index=0, multimodal=False, input='What is AI?', actual_output='AI (Artificial Intelligence) is technology that enables computers to learn, think, and make decisions like humans.  \nIt can recognize images, understand language, solve problems, and perform tasks.  \nExamples include chatbots, voice assistants, recommendation systems, and self-driving cars.', expected_output='AI (Artificial Intelligence) is the ability of computers to perform tasks that normally require human intelligence, such as learning, reasoning, recognizing patterns, and making decisions.', context=None, retrieval_context=None, turns=None, metadata=None),
 TestResult(name='test_case_1', success=True, metrics_data=[MetricData(name='Answer Correctness [GEval]', threshold=0.5, success=True, score=1.0, reason='The Actual Output accurately covers all key points from the Expected Output: it explains that traditional programming uses explicit, human-written rules, and that AI learns from data to make predictions or decisions. The summary sentence adds clarity without introducing errors. There are no incorrect facts or missing information.', strict_mode=False, flaky=False, evaluation_model='gpt-4.1', error=None, evaluation_cost=0.00129, input_tokens=369, output_tokens=69, verbose_logs='Criteria:\n\n    Evaluate whether the generated answer is factually correct\n    compared with the expected teacher answer.\n\n    Give a high score when the important meaning and facts are correct.\n\n    Penalize:\n    - incorrect facts\n    - contradictory information\n    - missing important information\n\n    Minor wording differences should not reduce the score.\n     \n \nEvaluation Steps:\n[\n    "Compare the Actual Output to the Expected Output to check if all important facts and information are correct and present.",\n    "Identify any incorrect facts, contradictions, or missing key information in the Actual Output compared to the Expected Output.",\n    "Ignore minor wording differences that do not affect the meaning or factual accuracy.",\n    "Assign a high score if the Actual Output accurately conveys the important meaning and facts from the Expected Output."\n] \n \nRubric:\nNone \n \nScore: 1.0'), MetricData(name='Answer Relevancy', threshold=0.5, success=True, score=1.0, reason=None, strict_mode=False, flaky=False, evaluation_model='gpt-4.1', error=None, evaluation_cost=0.00379, input_tokens=867, output_tokens=257, verbose_logs='Statements:\n[\n    "Traditional programming follows explicit rules written by humans to produce outputs from inputs.",\n    "AI learns patterns from examples and uses them to make predictions or decisions.",\n    "Traditional programs are rule-based.",\n    "AI is data-driven.",\n    "AI can improve with experience."\n] \n \nVerdicts:\n[\n    {\n        "verdict": "yes",\n        "reason": "This statement directly explains how traditional programming works, which is relevant to comparing it with AI."\n    },\n    {\n        "verdict": "yes",\n        "reason": "This statement describes how AI operates, which is central to the comparison with traditional programming."\n    },\n    {\n        "verdict": "yes",\n        "reason": "This statement highlights a key characteristic of traditional programming, relevant to the comparison."\n    },\n    {\n        "verdict": "yes",\n        "reason": "This statement succinctly contrasts AI with traditional programming by describing AI as data-driven."\n    },\n    {\n        "verdict": "yes",\n        "reason": "This statement is relevant because it points out a unique feature of AI (learning from experience), which is part of how it differs from traditional programming."\n    }\n]'), MetricData(name='Helpfulness [GEval]', threshold=0.5, success=True, score=1.0, reason='The response directly answers the question by contrasting traditional programming and AI, clearly stating that traditional programming is rule-based while AI is data-driven and learns from examples. The explanation is concise, easy to understand for a beginner, and avoids unnecessary information, fully aligning with all evaluation steps.', strict_mode=False, flaky=False, evaluation_model='gpt-4.1', error=None, evaluation_cost=0.001206, input_tokens=327, output_tokens=69, verbose_logs='Criteria:\n\n    Evaluate how helpful the generated answer is for a beginner student.\n\n    A helpful answer should:\n\n    1. Directly answer the student\'s question.\n    2. Be easy to understand.\n    3. Provide enough explanation.\n    4. Avoid unnecessary information.\n    5. Help the student understand the concept.\n     \n \nEvaluation Steps:\n[\n    "Check if the Actual Output directly answers the question in the Input.",\n    "Assess whether the Actual Output is easy to understand for a beginner student.",\n    "Determine if the Actual Output provides sufficient explanation to help the student grasp the concept.",\n    "Verify that the Actual Output avoids unnecessary or irrelevant information."\n] \n \nRubric:\nNone \n \nScore: 1.0')], conversational=False, index=1, multimodal=False, input='How does AI differ from traditional programming?', actual_output='Traditional programming follows explicit rules written by humans to produce outputs from inputs.  \nAI learns patterns from examples and uses them to make predictions or decisions.  \nIn short: traditional programs are rule-based, while AI is data-driven and can improve with experience.', expected_output='Traditional programs follow fixed rules written by humans. AI systems can learn patterns from data and use those patterns to make predictions or decisions.', context=None, retrieval_context=None, turns=None, metadata=None),
 TestResult(name='test_case_2', success=True, metrics_data=[MetricData(name='Answer Correctness [GEval]', threshold=0.5, success=True, score=0.9, reason="The Actual Output accurately explains that machine learning involves computers learning from data and making predictions without explicit programming, which aligns with the Expected Output. It also provides a relevant example (spam email detection), adding clarity. The only minor shortcoming is that it does not explicitly mention 'branch of AI' or 'decisions,' but these omissions do not significantly affect the core meaning.", strict_mode=False, flaky=False, evaluation_model='gpt-4.1', error=None, evaluation_cost=0.0014459999999999998, input_tokens=371, output_tokens=88, verbose_logs='Criteria:\n\n    Evaluate whether the generated answer is factually correct\n    compared with the expected teacher answer.\n\n    Give a high score when the important meaning and facts are correct.\n\n    Penalize:\n    - incorrect facts\n    - contradictory information\n    - missing important information\n\n    Minor wording differences should not reduce the score.\n     \n \nEvaluation Steps:\n[\n    "Compare the Actual Output to the Expected Output to check if all important facts and information are correct and present.",\n    "Identify any incorrect facts, contradictions, or missing key information in the Actual Output compared to the Expected Output.",\n    "Ignore minor wording differences that do not affect the meaning or factual accuracy.",\n    "Assign a high score if the Actual Output accurately conveys the important meaning and facts from the Expected Output."\n] \n \nRubric:\nNone \n \nScore: 0.9'), MetricData(name='Answer Relevancy', threshold=0.5, success=True, score=1.0, reason=None, strict_mode=False, flaky=False, evaluation_model='gpt-4.1', error=None, evaluation_cost=0.003202, input_tokens=865, output_tokens=184, verbose_logs='Statements:\n[\n    "Machine Learning is a way for computers to learn from examples and data.",\n    "Computers are not explicitly programmed for every task in Machine Learning.",\n    "The computer finds patterns and makes predictions.",\n    "Machine Learning can be used to identify spam emails by studying many examples."\n] \n \nVerdicts:\n[\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "yes",\n        "reason": null\n    },\n    {\n        "verdict": "idk",\n        "reason": "This statement provides an example of an application of Machine Learning, which is supporting information but not a direct definition or explanation of what Machine Learning is."\n    }\n]'), MetricData(name='Helpfulness [GEval]', threshold=0.5, success=True, score=1.0, reason='The response directly answers the question by defining machine learning in simple terms, making it accessible for a beginner. It provides a clear example (spam email detection) to illustrate the concept, aiding understanding. The explanation is concise and avoids irrelevant information, fully aligning with all evaluation steps.', strict_mode=False, flaky=False, evaluation_model='gpt-4.1', error=None, evaluation_cost=0.001196, input_tokens=322, output_tokens=69, verbose_logs='Criteria:\n\n    Evaluate how helpful the generated answer is for a beginner student.\n\n    A helpful answer should:\n\n    1. Directly answer the student\'s question.\n    2. Be easy to understand.\n    3. Provide enough explanation.\n    4. Avoid unnecessary information.\n    5. Help the student understand the concept.\n     \n \nEvaluation Steps:\n[\n    "Check if the Actual Output directly answers the question in the Input.",\n    "Assess whether the Actual Output is easy to understand for a beginner student.",\n    "Determine if the Actual Output provides sufficient explanation to help the student grasp the concept.",\n    "Verify that the Actual Output avoids unnecessary or irrelevant information."\n] \n \nRubric:\nNone \n \nScore: 1.0')], conversational=False, index=2, multimodal=False, input='What is Machine Learning?', actual_output='Machine Learning is a way for computers to learn from examples and data.  \nInstead of being explicitly programmed for every task, the computer finds patterns and makes predictions.  \nFor example, it can learn to identify spam emails by studying many examples.', expected_output='Machine Learning is a branch of AI where computers learn patterns from data and use those patterns to make predictions or decisions without being explicitly programmed for every case.', context=None, retrieval_context=None, turns=None, metadata=None),

In [7]:

for i, test_result in enumerate(result.test_results):

    metrics_data = test_result.metrics_data

    df.loc[i, "AnswerCorrectness"] = metrics_data[0].score
    df.loc[i, "AnswerRelevancy"] = metrics_data[1].score
    df.loc[i, "Helpfulness"] = metrics_data[2].score


# ============================================================
# 3. CALCULATE OVERALL ANSWER QUALITY
# ============================================================

df["AnswerQuality"] = (
    df["AnswerCorrectness"]
    + df["AnswerRelevancy"]
    + df["Helpfulness"]
) / 3


# ============================================================
# 4. ROUND SCORES
# ============================================================

metric_columns = [
    "AnswerCorrectness",
    "AnswerRelevancy",
    "Helpfulness",
    "AnswerQuality"
]

df[metric_columns] = df[metric_columns].round(3)


# ============================================================
# 5. AVERAGES
# ============================================================

average_correctness = df["AnswerCorrectness"].mean()
average_relevancy = df["AnswerRelevancy"].mean()
average_helpfulness = df["Helpfulness"].mean()
average_quality = df["AnswerQuality"].mean()


# ============================================================
# 6. QUESTION-WISE RESULTS
# ============================================================

print("\n")
print("=" * 120)
print("                         AI TEACHER ANSWER QUALITY")
print("=" * 120)

display_df = df[
    [
        "User Query",
        "AnswerCorrectness",
        "AnswerRelevancy",
        "Helpfulness",
        "AnswerQuality"
    ]
]


# ============================================================
# 8. SAVE FINAL RESULT
# ============================================================

df.to_csv(
    "ai_teacher_evaluation.csv",
    index=False,
    encoding="utf-8-sig"
)

========================================================================================================================
                         AI TEACHER ANSWER QUALITY
========================================================================================================================

In [8]:
df

,User Query,Teacher Response,GeneratedAnswer,AnswerCorrectness,AnswerRelevancy,Helpfulness,AnswerQuality
0,What is AI?,AI (Artificial Intelligence) is the ability of...,AI (Artificial Intelligence) is technology tha...,0.890,1.000,1.000,0.963
1,How does AI differ from traditional programming?,Traditional programs follow fixed rules writte...,Traditional programming follows explicit rules...,1.000,1.000,1.000,1.000
2,What is Machine Learning?,Machine Learning is a branch of AI where compu...,Machine Learning is a way for computers to lea...,0.900,1.000,1.000,0.967
3,What is Deep Learning?,Deep Learning is a type of Machine Learning th...,Deep Learning is a type of AI that uses artifi...,0.729,1.000,1.000,0.910
4,"What is the difference between AI, ML, and Dee...",AI is the broad field of making machines intel...,AI is the broad idea of making computers perfo...,0.900,1.000,1.000,0.967
5,What is training data?,Training data is the data used to teach a Mach...,Training data is the information used to teach...,0.900,1.000,1.000,0.967
6,What is a Machine Learning model?,A Machine Learning model is a mathematical sys...,A machine learning model is a computer program...,0.900,1.000,1.000,0.967
7,What is supervised learning?,Supervised learning trains a model using examp...,Supervised learning is a type of machine learn...,0.900,1.000,0.998,0.966
8,What is unsupervised learning?,Unsupervised learning works with data that doe...,Unsupervised learning is a type of machine lea...,0.969,1.000,1.000,0.990
9,What is reinforcement learning?,Reinforcement learning teaches an agent throug...,Reinforcement learning is a type of machine le...,1.000,1.000,0.900,0.967
10,What is an LLM?,"An LLM, or Large Language Model, is an AI mode...",An LLM (Large Language Model) is an AI trained...,0.980,1.000,1.000,0.993
11,What is Generative AI?,Generative AI is AI that can create new conten...,Generative AI is technology that creates new c...,0.900,1.000,1.000,0.967
12,What is a prompt?,A prompt is the instruction or input given to ...,"A prompt is a question, instruction, or messag...",0.900,1.000,1.000,0.967
13,What is Prompt Engineering?,Prompt Engineering is the practice of designin...,Prompt engineering is the skill of writing cle...,0.834,1.000,1.000,0.945
14,What is RAG?,RAG stands for Retrieval-Augmented Generation....,RAG (Retrieval-Augmented Generation) helps AI ...,0.900,1.000,1.000,0.967
15,Why is RAG useful?,RAG is useful when an AI application needs to ...,RAG lets an AI search trusted documents before...,0.700,1.000,0.948,0.883
16,What is a vector database?,A vector database stores numerical representat...,A vector database stores information as number...,0.887,1.000,0.921,0.936
17,What are embeddings?,Embeddings are numerical representations of te...,"Embeddings are numbers that represent words, i...",0.901,1.000,0.967,0.956
18,What is an AI Agent?,An AI Agent is a system that can understand a ...,An AI agent is a computer program that can und...,0.900,0.571,1.000,0.824
19,How can AI be used in education?,AI can support education by explaining concept...,AI can personalize lessons by adapting to each...,0.775,1.000,0.996,0.924

In [15]:
average_result=pd.DataFrame(columns=["average_correctness","average_relevancy","average_helpfulness","average_quality"],
                            data=[[average_correctness,average_relevancy,average_helpfulness,average_quality]])

In [16]:
average_result

,average_correctness,average_relevancy,average_helpfulness,average_quality
0,0.87875,1.0,0.9985,0.9591